version: '3'

services:
  de-final-prj-local:
    build:
      context: ./src
    image: src:local
    ports:
      - 8998:8998
      - 8280:8280
      - 15432:5432
    volumes:
      - "./src/sql:/lessons/sql:ro"
      - "./src/dags:/lessons/dags:ro"
      - "./src/plugins/vertica-jdbc-11.0.2-0.jar:/opt/metabase/plugins/vertica-jdbc-11.0.2-0.jar:ro"